[package]
name = "vecadd"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { git="https://github.com/rust-gpu/rust-cuda" }
nanorand = "0.7"

[build-dependencies]
cuda_builder = { git="https://github.com/rust-gpu/rust-cuda", features=["rustc_codegen_nvvm"] }
